FROM ruby:3.4.6

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

RUN apt-get update -qq \
  && apt-get install -y ca-certificates curl gnupg \
  && mkdir -p /etc/apt/keyrings \
  && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
  && NODE_MAJOR=24 \
  && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
  && apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs vim git

RUN mkdir /app
WORKDIR /app

# キャッシュ
COPY Gemfile Gemfile.lock ./

# Bundlerを更新
RUN gem install bundler

RUN bundle install

COPY . /app